obj-y += core.o init_util.o energy.o multi_load.o ontime.o load_balance.o
obj-y += global_boost.o
obj-y += freqvar_tune.o
obj-y += service.o
obj-$(CONFIG_CPU_FREQ_GOV_ENERGYSTEP) += energy_step.o
#obj-$(CONFIG_SCHED_USE_FLUID_RT) += frt.o
