# SPDX-License-Identifier: GPL-2.0
# CAL
obj-$(CONFIG_CAL_IF)		+= cal-if/
obj-$(CONFIG_EXYNOS_PD)        += exynos-pd.o exynos-pd-dbg.o

obj-$(CONFIG_ECT)		+= ect_parser.o
obj-$(CONFIG_EXYNOS_PMU)	+= exynos-pmu.o

obj-$(CONFIG_EXYNOS_PMU_ARM_DRIVERS)	+= exynos3250-pmu.o exynos4-pmu.o \
					exynos5250-pmu.o exynos5420-pmu.o
# ACPM
obj-$(CONFIG_EXYNOS_ACPM)       += acpm/

obj-$(CONFIG_EXYNOS_FLEXPMU_DBG)        += exynos-flexpmu-dbg.o
obj-$(CONFIG_EXYNOS_PM_DOMAINS) += pm_domains.o
obj-$(CONFIG_EXYNOS_CHIPID)	+= exynos-chipid.o

# ECT
obj-$(CONFIG_ECT)               += ect_parser.o

# reboot
obj-$(CONFIG_EXYNOS_REBOOT)	+= exynos-reboot.o

# USI_V2
obj-$(CONFIG_USI_V2)		+= usi_v2.o

obj-$(CONFIG_EXYNOS_CHIPID_V2)  += exynos-chipid_v2.o

obj-$(CONFIG_EXYNOS_SEH)        += exynos-seh.o

obj-$(CONFIG_EXYNOS_PD_EL3)     += exynos-pd_el3.o
obj-$(CONFIG_EXYNOS_SECURE_LOG) += exynos-seclog.o

obj-$(CONFIG_EXYNOS_TZASC_FAIL_DETECTOR) += exynos-tzasc.o

# SDM
obj-$(CONFIG_EXYNOS_SDM)	+= exynos-sdm.o
